# Generated by Django 4.2.7 on 2025-10-30 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("filename", models.CharField(max_length=255)),
                ("width", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("file_size", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("circularity", "Circularity Detection"),
                            ("hough", "Hough Circle Transform"),
                            ("blob", "Blob Detection"),
                        ],
                        max_length=50,
                    ),
                ),
                ("coins_detected", models.IntegerField(default=0)),
                ("processing_time", models.FloatField(default=0.0)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("true_positives", models.IntegerField(blank=True, null=True)),
                ("false_positives", models.IntegerField(blank=True, null=True)),
                ("false_negatives", models.IntegerField(blank=True, null=True)),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="results/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="detector.uploadedimage",
                    ),
                ),
            ],
            options={
                "ordering": ["algorithm"],
            },
        ),
        migrations.CreateModel(
            name="DetectedCoin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("center_x", models.FloatField()),
                ("center_y", models.FloatField()),
                ("radius", models.FloatField()),
                ("circularity", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to="detector.detectionresult",
                    ),
                ),
            ],
        ),
    ]
