# Generated by Django 4.2.7 on 2025-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("circularity", "Morphological Circularity Detection"),
                    ("hough", "Hough Circle Transform"),
                    ("blob", "Blob Detection"),
                ],
                max_length=50,
            ),
        ),
    ]
