# Generated by Django 4.2.7 on 2025-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_alter_detectionresult_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionresult",
            name="f1_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionresult",
            name="mean_iou",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
